server:
  port: 2333

lavalink:
  server:
    password: "${LAVALINK_PASSWORD}"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    resamplingQuality: HIGH
    filterHotSwap: true

metrics:
  prometheus:
    enabled: false
  logging:
    file: false
